# Macro file for 009_stackediteration9_onlysolarwind_from_00_num500
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/sphere/worldX 1240.0 um
/sphere/worldY 760 um
/sphere/worldZ 919.615 um
#
/run/initialize
/sphere/rootinput/file 000_stackediteration0_onlysolarwind_num500.root 001_stackediteration1_onlysolarwind_from_00_num500.root 002_stackediteration2_onlysolarwind_from_00_num500.root 003_stackediteration3_onlysolarwind_from_00_num500.root 004_stackediteration4_onlysolarwind_from_00_num500.root 005_stackediteration5_onlysolarwind_from_00_num500.root 006_stackediteration6_onlysolarwind_from_00_num500.root 007_stackediteration7_onlysolarwind_from_00_num500.root 008_stackediteration8_onlysolarwind_from_00_num500.root
/sphere/filename root/009_stackediteration9_onlysolarwind_from_00_num500.root
/sphere/cadinput/file stacked_spheres_frompython.stl
/sphere/epsilon 4
/sphere/PBC true
/run/initialize
#
/gps/particle proton
/gps/ene/type Mono
/gps/energy 1 keV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 450.0 um
/gps/pos/halfy 300.0 um
/gps/pos/centre 180.0 0 459.8075 um
/gps/direction -0.7071067811865475 0 -0.7071067811865475 
#
/gps/source/add 1
/gps/particle e-
/gps/source/intensity 5
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file electron_distribution.txt
/gps/hist/inter Lin
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 450.0 um
/gps/pos/halfy 300.0 um
/gps/pos/centre 0 0 459.8075 um
/gps/ang/type iso
#
#
/run/printProgress 100
/run/beamOn 500
