# Macro file for 058_stackediteration8_onlyphotoemission_from_00_num5000
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/sphere/worldX 200 um
/sphere/worldY 600 um
/sphere/worldZ 606.41 um
/sphere/fieldMapStep 10 um
#
/sphere/rootinput/file 050_stackediteration0_onlyphotoemission_num5000.root 051_stackediteration1_onlyphotoemission_from_00_num5000.root 052_stackediteration2_onlyphotoemission_from_00_num5000.root 053_stackediteration3_onlyphotoemission_from_00_num5000.root 054_stackediteration4_onlyphotoemission_from_00_num5000.root 055_stackediteration5_onlyphotoemission_from_00_num5000.root 056_stackediteration6_onlyphotoemission_from_00_num5000.root 057_stackediteration7_onlyphotoemission_from_00_num5000.root
/sphere/filename root/058_stackediteration8_onlyphotoemission_from_00_num5000.root
/sphere/cadinput/file stacked_spheres_frompython.stl
/sphere/epsilon 4
/sphere/PBC true
/run/initialize
#
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 100.0 um
/gps/pos/halfy 300.0 um
/gps/pos/centre 30.0 0 303.205 um
/gps/direction -0.7071067811865475 0 -0.7071067811865475 
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file photon_distribution.txt
/gps/hist/inter Lin
#
/run/printProgress 100
/run/beamOn 5000
