# Macro file for 09_stackediteration9_onlyphotoemission_from_00_num10000
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
/cuts/setLowEdge 5 eV
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/lowestElectronEnergy 10 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/sphere/rootinput/file 00_stackediteration0_onlyphotoemission_num10000.root 01_stackediteration1_onlyphotoemission_from_00_num10000.root 02_stackediteration2_onlyphotoemission_from_00_num10000.root 03_stackediteration3_onlyphotoemission_from_00_num10000.root 04_stackediteration4_onlyphotoemission_from_00_num10000.root 05_stackediteration5_onlyphotoemission_from_00_num10000.root 06_stackediteration6_onlyphotoemission_from_00_num10000.root 07_stackediteration7_onlyphotoemission_from_00_num10000.root 08_stackediteration8_onlyphotoemission_from_00_num10000.root
/sphere/filename root/09_stackediteration9_onlyphotoemission_from_00_num10000.root
/sphere/cadinput/file stacked_spheres_frompython.stl
/sphere/epsilon 3.9
/sphere/PBC false
#
/run/initialize
#
/gps/particle e-
/gps/source/intensity 1 # Relative intensity of the gamma source
/gps/ene/type Mono
/gps/energy 120 eV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 400 um
/gps/pos/halfy 400 um
/gps/pos/centre 300 -300 800 um
/gps/direction 0 0 -1
/gps/ang/type planar
#
/gps/source/add 1
/gps/source/intensity 100 # Relative intensity of the gamma source
/gps/particle gamma
/gps/ene/type Mono
/gps/energy 10 eV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 400 um
/gps/pos/halfy 400 um
/gps/pos/centre 300 -300 800 um
/gps/direction 0 0 -1
/gps/ang/type planar
#
/run/printProgress 100
/run/beamOn 10000
