# Macro file for 209_stackediteration9_onlyphotoemission_from_00_num5000
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/sphere/worldX 900 um
/sphere/worldY 600 um
/sphere/worldZ 800 um
/sphere/rootinput/file 200_stackediteration0_onlyphotoemission_num5000.root 201_stackediteration1_onlyphotoemission_from_00_num5000.root 202_stackediteration2_onlyphotoemission_from_00_num5000.root 203_stackediteration3_onlyphotoemission_from_00_num5000.root 204_stackediteration4_onlyphotoemission_from_00_num5000.root 205_stackediteration5_onlyphotoemission_from_00_num5000.root 206_stackediteration6_onlyphotoemission_from_00_num5000.root 207_stackediteration7_onlyphotoemission_from_00_num5000.root 208_stackediteration8_onlyphotoemission_from_00_num5000.root
/sphere/filename root/209_stackediteration9_onlyphotoemission_from_00_num5000.root
/sphere/cadinput/file stacked_spheres_frompython.stl
/sphere/epsilon 4
/sphere/PBC true
#
/run/initialize
#
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 450.0 um
/gps/pos/halfy 300.0 um
/gps/pos/centre -224.99999999999997 0 600 um
/gps/direction 0.7071067811865475 0 -0.7071067811865475 
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file photon_distribution.txt
/gps/hist/inter Lin
#
/run/printProgress 100
/run/beamOn 5000
