# Macro file for 21_stackediteration9_onlyphotoemission_from_00_num10000
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
/cuts/setLowEdge 5 eV
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 10 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/sphere/rootinput/file 12_stackediteration0_onlyphotoemission_num10000.root 13_stackediteration1_onlyphotoemission_from_00_num10000.root 14_stackediteration2_onlyphotoemission_from_00_num10000.root 15_stackediteration3_onlyphotoemission_from_00_num10000.root 16_stackediteration4_onlyphotoemission_from_00_num10000.root 17_stackediteration5_onlyphotoemission_from_00_num10000.root 18_stackediteration6_onlyphotoemission_from_00_num10000.root 19_stackediteration7_onlyphotoemission_from_00_num10000.root 20_stackediteration8_onlyphotoemission_from_00_num10000.root
/sphere/filename root/21_stackediteration9_onlyphotoemission_from_00_num10000.root
/sphere/cadinput/file stacked_spheres_frompython.stl
/sphere/epsilon 3.9
/sphere/PBC false
#
/run/initialize
#
/gps/particle e-
/gps/source/intensity 1 # Relative intensity of the gamma source
/gps/ene/type Mono
/gps/energy 120 eV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 400 um
/gps/pos/halfy 400 um
/gps/pos/centre 0 0 800 um
/gps/direction 0 0 -1
/gps/ang/type planar
#
/gps/source/add 1
/gps/source/intensity 100 # Relative intensity of the gamma source
/gps/particle gamma
/gps/ene/type Mono
/gps/energy 10 eV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 400 um
/gps/pos/halfy 400 um
/gps/pos/centre 0 0 800 um
/gps/direction 0 0 -1
/gps/ang/type planar
#
/run/printProgress 100
/run/beamOn 10000
