# Macro file for testing photons
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#/cuts/setLowEdge 70 keV
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/geometry/worldX 400 um
/geometry/worldY 300 um
/geometry/worldZ 453.2 um
/geometry/MaterialTemperature 425 K
/geometry/MaterialDensity 2.2 g/cm3
/geometry/IterationTime 0 s
/geometry/ApplyChargeDissipation true
/field/InitialDepth 8
/field/MinimumStep 0.05 um
/field/PercentGradThreshold 0.8
/field/OctreeDepth 11
/field/file test-fieldmap.txt 
/charges/file test-charges.txt
#
/geometry/rootoutput/file test-rootOutput.root
/geometry/cadinput/file regularSpheres_fromPython.stl
/geometry/epsilon 4
/geometry/PBC true
#/geometry/cadinput/scale 0.001
/run/initialize
#
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 200.0 um
/gps/pos/halfy 150.0 um
/gps/pos/centre 40.0 0 226.6 um
/gps/direction -0.7071067811865476 0 -0.7071067811865476
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file distributions/photonSolar_distribution.txt
/gps/hist/inter Lin
#
/control/execute test-macros/vis.mac
#
/run/printProgress 100
/run/beamOn 30
