# Macro file for testing photons
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#/cuts/setLowEdge 70 keV
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 10 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/geometry/worldX 120 um
/geometry/worldY 105 um
/geometry/worldZ 202 um
/geometry/MaterialTemperature 425 K
/geometry/MaterialDensity 1.9 g/cm3
/geometry/IterationTime 0 s
/geometry/ApplyChargeDissipation true
/field/InitialDepth 8
/field/MinimumStep 0.01 um
/field/PercentGradThreshold 0.8
/field/OctreeDepth 11
/field/file test-fieldmap.txt 
/charges/file test-charges.txt
#
/geometry/rootoutput/file test-rootOutput.root
/geometry/cadinput/file irregularSpheres_fromPython.stl
/geometry/epsilon 4
/geometry/PBC true
#/geometry/cadinput/scale 0.001
/run/initialize
#
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 60.0 um
/gps/pos/halfy 52.5 um
/gps/pos/centre 50 0 101.0 um
#/gps/pos/centre 15.0 0 83.5 um
/gps/direction -0.7071067811865475 0 -0.7071067811865475 
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file distributions/photonSolar_distribution.txt
/gps/hist/inter Lin
#
/control/execute test-macros/vis.mac
#
/run/printProgress 100
/run/beamOn 100
