# Macro file for 000_iteration0_onlyphotoemission_num50000
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/had/verbose 0
/process/em/verbose 0
#
/random/setSeeds 10008859 10005380
/random/setSavingFlag 1
#
/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true
/process/em/deexcitationIgnoreCut true
/process/em/Polarisation true
/process/em/PhotoeffectBelowKShell true
#
/process/em/lowestElectronEnergy 0 eV
/process/em/lowestMuHadEnergy 100 eV
/process/em/enableSamplingTable 1
#
/process/eLoss/CSDARange 1
/process/eLoss/UseICRU90 1
/process/eLoss/UseAngularGenerator true
#
/geometry/worldX 107.00044 um
/geometry/worldY 120.77438 um
/geometry/worldZ 180.29045000000002 um
/geometry/MaterialTemperature 425 K
/geometry/MaterialDensity 1.9 g/cm3
/geometry/IterationTime 0 s
/geometry/ApplyChargeDissipation true
/field/InitialDepth 8
/field/MinimumStep 0.01 um
/field/PercentGradThreshold 0.7
/field/OctreeDepth 11
/field/file test-fieldmap.txt 
/charges/file test-charges.txt
#
/geometry/rootoutput/file testOutput.root
/geometry/cadinput/file irealisticGrains_fromPython.stl
/geometry/epsilon 4
/geometry/PBC true
/run/initialize
#
/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 53.50022 um
/gps/pos/halfy 60.38719 um
/gps/pos/centre 40.00000000000001 0 90.14522500000001 um
/gps/direction -0.7071067811865476 0 -0.7071067811865476
/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/diffspec true
/gps/hist/file distributions/photonSolar_distribution.txt
/gps/hist/inter Lin
#
/control/execute test-macros/vis.mac
#
/run/printProgress 5000
#/run/beamOn 100
